# Generated by Django 3.2.23 on 2024-05-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
