# Generated by Django 3.2.23 on 2024-06-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0002_rename_name_register_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=25)),
                ('adminpassword', models.CharField(max_length=30)),
            ],
        ),
    ]
