# Generated by Django 3.2.23 on 2024-06-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0003_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='a_name',
            new_name='admin_name',
        ),
    ]
