# Generated by Django 3.2.23 on 2024-06-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0004_rename_a_name_admin_admin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
