# Generated by Django 3.2.23 on 2024-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
