# Generated by Django 3.2.23 on 2024-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0008_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
