# Generated by Django 3.2.23 on 2024-06-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0009_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
