# Generated by Django 3.2.23 on 2024-06-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0011_alter_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('about_doc', models.CharField(max_length=255)),
                ('admin_doc', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
