# Generated by Django 3.2.23 on 2024-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0012_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_flash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
