# Generated by Django 3.2.23 on 2024-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0013_flashnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='add_doc',
            field=models.FileField(max_length=254, null=True, upload_to='media/'),
        ),
    ]
