# Generated by Django 3.2.23 on 2024-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0014_document_add_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='add_doc',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='media/'),
        ),
    ]
