# Generated by Django 3.2.23 on 2024-06-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0015_alter_document_add_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
