# Generated by Django 3.2.23 on 2024-06-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0016_register_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gfeedback_username', models.TextField()),
                ('gfeedback_email', models.CharField(max_length=50)),
                ('gfeedback_contactno', models.CharField(max_length=10)),
                ('gfeedback_eventname', models.TextField()),
                ('gfeedback', models.TextField()),
            ],
        ),
    ]
