# Generated by Django 3.2.23 on 2024-06-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0017_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
