# Generated by Django 3.2.23 on 2024-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0018_auto_20240618_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videogallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos/')),
                ('video_link', models.URLField(blank=True)),
            ],
        ),
    ]
