# Generated by Django 3.2.23 on 2024-06-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0021_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateField()),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_authorName', models.CharField(max_length=100)),
                ('blog_authorRole', models.CharField(max_length=150)),
                ('blog_author_image', models.ImageField(blank=True, null=True, upload_to='Author/')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
