# Generated by Django 3.2.23 on 2024-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0022_auto_20240626_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_information',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_sub_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_sub_information',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_authorRole',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
