# Generated by Django 3.2.23 on 2024-06-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0023_auto_20240626_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_authorRole',
            field=models.CharField(max_length=150),
        ),
    ]
