# Generated by Django 3.2.23 on 2024-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0024_alter_blogs_blog_authorrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_information',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_sub_information',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
