# Generated by Django 3.2.23 on 2024-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0026_auto_20240701_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
