# Generated by Django 3.2.23 on 2024-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0027_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_eventsregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_eventusername', models.CharField(max_length=255)),
                ('public_eventage', models.CharField(max_length=2)),
                ('public_eventcontactno', models.CharField(max_length=10, unique=True)),
                ('public_eventgender', models.CharField(max_length=10)),
                ('public_eventemail', models.EmailField(max_length=255, unique=True)),
                ('public_eventname', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_active',
        ),
    ]
