# Generated by Django 3.2.23 on 2024-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0028_auto_20240703_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
