# Generated by Django 3.2.23 on 2024-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0029_register_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.AlterField(
            model_name='public_eventsregister',
            name='public_eventemail',
            field=models.EmailField(max_length=255),
        ),
    ]
