# Generated by Django 3.2.23 on 2024-07-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0031_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='members_eventregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contactno', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
    ]
