# Generated by Django 3.2.23 on 2024-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0033_eventfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_eventregister',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
