# Generated by Django 3.2.23 on 2024-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0034_alter_members_eventregister_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_eventregister',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='public_eventsregister',
            name='public_eventcontactno',
            field=models.CharField(max_length=10),
        ),
    ]
