# Generated by Django 3.2.23 on 2024-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0035_auto_20240711_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_eventregister',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
