# Generated by Django 3.2.23 on 2024-07-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0036_alter_members_eventregister_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members_eventregister',
        ),
    ]
