# Generated by Django 3.2.23 on 2024-07-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0038_members_eventregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
