# Generated by Django 3.2.23 on 2024-07-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0042_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
