# Generated by Django 3.2.23 on 2024-07-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0043_event_meeting_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members_eventregister',
        ),
    ]
