# Generated by Django 3.2.23 on 2024-07-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0044_delete_members_eventregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='members_eventregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contactno', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A1App.event')),
            ],
        ),
    ]
