# Generated by Django 3.2.23 on 2024-07-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0045_members_eventregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members_eventregister',
        ),
    ]
