# Generated by Django 3.2.23 on 2024-07-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0049_members_eventregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_eventregister',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='members_eventregister',
            name='event_time',
        ),
    ]
