# Generated by Django 3.2.23 on 2024-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0051_trainings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=255)),
                ('training_description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='training_video/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('training_image', models.ImageField(blank=True, null=True, upload_to='training_image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Trainings',
        ),
    ]
