# Generated by Django 3.2.23 on 2024-07-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0052_auto_20240725_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
