# Generated by Django 3.2.23 on 2024-07-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0053_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
    ]
