# Generated by Django 3.2.23 on 2024-07-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0054_event_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('eventname', models.TextField()),
                ('event_feedback', models.TextField()),
            ],
        ),
    ]
