# Generated by Django 3.2.23 on 2024-08-15 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0055_event_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Age must be 18 or above.')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='contactno',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^[0-9]{10}$')]),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='register_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
    ]
