# Generated by Django 3.2.23 on 2024-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0057_auto_20240815_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
