# Generated by Django 3.2.23 on 2024-08-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0058_member_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_link',
        ),
    ]
