# Generated by Django 3.2.23 on 2024-08-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0060_alter_training_training_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
