# Generated by Django 3.2.23 on 2024-08-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0063_auto_20240818_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
