# Generated by Django 3.2.23 on 2024-08-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0065_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='member',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
