# Generated by Django 3.2.23 on 2024-08-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0067_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
