# Generated by Django 3.2.23 on 2024-08-19 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0069_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='by',
            field=models.CharField(default=0, max_length=255, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Only letters and spaces are allowed')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('email',)},
        ),
    ]
