# Generated by Django 3.2.23 on 2024-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0070_auto_20240819_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
