# Generated by Django 3.2.23 on 2024-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1App', '0072_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
